### ISSUE TITLE
With Arabic set as browser/system language, ExtendedQueryParameters.ToTridionQuery() fail

### ISSUE THREAD

**Issue by patrykgliwinski** [dd4t/dynamic-delivery-4-tridion#26]
With Arabic set as browser/system language, ExtendedQueryParameters.ToTridionQuery() method fails with the following trace:

2015-09-23 15:12:05,179 [118] ERROR Core.Helpers.HtmlHelperExtensions - HtmlHelperExtensions
System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive.
Parameter name: time
   at System.Globalization.UmAlQuraCalendar.CheckTicksRange(Int64 ticks)
   at System.Globalization.UmAlQuraCalendar.GetDatePart(DateTime time, Int32 part)
   at System.DateTimeFormat.FormatCustomized(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at DD4T.Providers.SDLTridion2011sp1.ExtendedQueryParameters.ToTridionQuery()
   at DD4T.Providers.SDLTridion2011sp1.TridionComponentProvider.FindComponents(IQuery query)
...

Pull Request:
https://github.com/dd4t/dynamic-delivery-4-tridion/pull/27

**Comment by quirijnslings** [comment]
@patrykgliwinski We won't fix this in the DD4T 1.\* codeline anymore, please upgrade to 2.0.
See https://github.com/dd4t/DD4T.Providers.SDLTridion2011sp1/issues/5
